### ISSUE TITLE
eurobench interface

### ISSUE THREAD

**Issue by aremazeilles** [CentroEPiaggio/dysturbance#13]
Hi @simomonte 

Could you confirm that the function `Compute_Local_PI` is the only function to call to get the PIs computed?
With that function, we get values for `absorbed_energy`, `fall_check` and `stability_margin`. 

If ok, I can work on the interface to call it from eurobench framework.
It seems the code cannot be directly launched from octave, as it uses function that are not present in octave (such as `readtable`).
We have an alternative to deal with pure matlab code, I can deploy it. 

I would just wait for you to confirm that the 3 PIs mentioned are the only one, so that I can then focus on the 2nd point.

**Comment by simomonte** [comment]
Hi Anthony! Basically, the values you get depend on the protocol related to the data file. For example, if you run protocol three, you won't get "absorbed energy", but you will get values for "stability_margin", "fall_check", and "equivalent_impedance".
I can list all the values that result from each protocol if you need them.

**Comment by simomonte** [comment]
Moreover, Compute_Local_PI is the function that computes the PIs related to a single data file. Conversely, Compute_Global_PI calculates the PIs related to the whole set of data files related to a specific Protocol.
If I remember correctly, during our call, we talked about using Compute_Local_PI as the main function for the eurobench framework.

**Comment by aremazeilles** [comment]
From the vision, I have, your code is associated with four protocols: see https://github.com/eurobench/eurobench_protocol#dysturbance

But from your experimental data, I see that you have 5 protocols. Is this right?

I would indeed to know for each of the 4 (or 5) protocols, which are the metrics generated (we need to know this, as we complete the website with such information). 

If we stick to `compute_local_PI` as entry point for eurobench, then I can look at the deploy mechanism. But the info protocol->Pis is still of relevance for us. Thanks!

**Comment by simomonte** [comment]
Yes, the protocols are five. Enlisting it with the output values, we have:
1. Impulsive Disturbance --> absorbed_energy, fall_check, stability_margin;
2. Sinusoidal CoM Displacement Perturbation --> fall_check, stability_margin;
3. Sinusoidal Force Disturbance --> fall_check, stability_margin, equivalent_Impedance;
4. Quasi-Static CoM Displacement Perturbation --> fall_check, stability_margin;
5. Quasi-Static Force Disturbance --> fall_check, stability_margin;

**Comment by aremazeilles** [comment]
Once #12 and #14 will be merged, we should be ok on the code site.
Then I would, if you permit, clone your repository into https://github.com/eurobench/ , as it is done with others.
I use it to detect code evolution along time. 

Then we may need to update the protocol description, at least to add the missing one. From https://github.com/eurobench/eurobench_protocol#dysturbance 
you can access to the 4 protocol descriptions we have so far:


* [Dysturbance -Reaction to Impulsive Disturbance](https://platform.eurobench2020.eu/protocols/info/39)
* [Dysturbance - Reaction to Sinusoidal Force Disturbance](https://platform.eurobench2020.eu/protocols/info/40)
* [Dysturbance - Reaction to Sinusoidal displacement Disturbance](https://platform.eurobench2020.eu/protocols/info/41)
* [Dysturbance - Reaction to external Quasistatic Disturbance](https://platform.eurobench2020.eu/protocols/info/40)

 All were extracted from the [excel sheet](https://github.com/eurobench/eurobench_protocol/blob/main/data/dysturbance/dysturbance.xlsx) you provided a while ago.

It seems we only have a description for _external quasistatic dysturbance_ while you differentiate _COM displacement perturbation_ and _force disturbance_, correct?

**Comment by simomonte** [comment]
Yes, the framework considers these protocols as two different experiments. If you need I can also adjust the excel sheet.

**Comment by aremazeilles** [comment]
That would be great if you could introduce this 5th protocol in the excel sheet.
Also, we usually share with the protocols the computed metrics, which is why we aimed for in the Pi-PiAlgo sheet.

From what you mentioned in a previous post, you compute 4 different  metrics across these 5 protocols:

 absorbed_energy, fall_check, stability_margin, equivalent_Impedance

Could you revise the Pi-Pi Algo sheet to briefly describe these 4 metrics ? Then we could add it to the eurobench platform

**Comment by simomonte** [comment]
Hi Anthony! I adjust the datasheet with the correction you requested. I have only one concern. 
The PIs that we called stability_margin for aggregation express the same conceptual meaning for each protocol, but they are actually computed in different ways. Therefore, aggregating them in a unique definition is not trivial, as they are expressed differently (e.g. quasi-static is scalar while sinusoidal is a matrix). What do you suggest for them?

**Comment by aremazeilles** [comment]
I would suggest to put 2 definition, eventually the 2nd referencing to the 1st one if similar, but highlighting the difference with the previous one

**Comment by simomonte** [comment]
Hi Anthony! I was trying to adjust the metrics as u requested, but I found another Issue. When merging the stability margins depending on if they are scalars or matrices, I pointed out the different units these measures possess. Therefore, I was thinking if it can be feasible for you to maintain the existing division while calling them "Stability margin - Impulsive Loads", or "Stability Margin - Quasi-Static Forces" and so on. Let me know, or else I will proceed to merge the definitions as you previously asked.

**Comment by aremazeilles** [comment]
Hello, sorry for my late answer. I am afraid I am ot sure to understand your concern. 

At the end of the day, what we need is to have a link in between:

* the protocol
* the algorithm launched
* the metric computed.

i.e if we use the protocol X, the metric is provided by algorithm A_x (several possible). A_X computes metrics m_1, m_2 and m_3 --> we can deduce that following protocol X, we will get the metrics m_1, m_2 and m_3

For m_1, m_2 and m_3 we ask for a definition

Note that another protocol P2 may be connected to n_1, n_2 and n_3
I understand m_1 and n_1 could be your `stability_margin` case, for which m_1 is the scalar version, while n_1 is the matrix.
This is not a problem, as long as you create the table for m_1 and the one for n_1 separately (even if the content is very similar).

If unclear, I would suggest you to send me your current excel file, and then we could arrange a meeting to clarify lively these doubts

**Comment by aremazeilles** [comment]
Please have a look at: 
[dysturbance_template.xlsx](https://github.com/CentroEPiaggio/dysturbance/files/8246987/dysturbance_template.xlsx)

In the protocol sheet, I added a table to distinguish the Quasistatic displacement and Force.

Then I created a PI-PI Algo_proposal, to not touch at your orginal sheet.

I introduced a table for each Pi of each protocol (just with the name, the rest could be copy-paste from the original when appropriate).
With such structure, each PI metrics is fully related to a given protocol. If one metric is repeated in several protocol (both in description and format), then you could merge them (updating as well the algorithm section).
The algorithm section seems a bit virtual here, as in your case the same algorithms any of the protocols. But this is the way we structure it. As you can see, all algorithm use indeed the same command to launch your code. But they relate to the Pi of the protocol they are associated to.

Let me know if this makes it clearer for you (or if it is worse :) )

What would be remaining there is to check the two last protocol (quasistatic), and to complete the PI descriptions, factorizing across protocols the ones that are strictly speaking the same.

**Comment by aremazeilles** [comment]
Hello
I would like to progress on this. Do you have any issue filling the excel sheet? We can arrange a video call to clarify any doubt.
Thanks

**Comment by simomonte** [comment]
Hi Anthony, I have Corrected the datasheet with the information you needed. Let me know if it is ok like this.
You can find it in: https://www.dropbox.com/s/rl6zz51h067g535/dysturbance_template%20%281%29.xlsx?dl=0
Sorry for the delay.
Simone

**Comment by aremazeilles** [comment]
Thanks, I am working on it. May have some suggestions: 

Yoo indicated me the following association: 

> 1. Impulsive Disturbance --> absorbed_energy, fall_check, stability_margin;
> 2. Sinusoidal CoM Displacement Perturbation --> fall_check, stability_margin;
> 3. Sinusoidal Force Disturbance --> fall_check, stability_margin, equivalent_Impedance;
> 4. Quasi-Static CoM Displacement Perturbation --> fall_check, stability_margin;
> 5. Quasi-Static Force Disturbance --> fall_check, stability_margin;

But when I run `Compute_local_PI` with data of the 5 protocols, I get:

- 1- Absorbed_energy.yaml --> vector
  - Fall check --> scalar (stored as a vector
  - stability --> vector
- 2
  - Equivalent_impedance.yaml --> vector
  - Fall check --> scalar (stored as a vector
  -  Stability_margin.yaml --> vector
- 3
  - Equivalent_impedance.yaml --> vector
  - Fall check --> scalar (stored as a vector
  -  Stability_margin.yaml --> vector
- 4 
  - Fall check --> scalar (stored as a vector
  - stability --> vector
- 5
  - Fall check --> scalar (stored as a vector
  - stability --> vector

So I would assume that for protocol 2 we also compute the equivalence impedance.

For our automation process, we can factorize definition of PI if they are always the same. That would work for fall_check, which is always of the same shape.

For `Stability Margin` and `Equivalent_impedance`, the output is always a vector, but the number (and label) of entries differ.

I will check with my colleague whether we can handle it as is. Otherwise we may have to change the name of the stored file (we associate the pi name and the pi file, they have to be equivalent).

**Comment by aremazeilles** [comment]
Hello
At the end, the simpliest for us is to define an unique PI for all Stability_margin and Fall_check ... This is how we are going to embed it into the eurobench system

I think we can close this then, thanks a lot!
