### ISSUE TITLE
Global Readme

### ISSUE THREAD

**Issue by aremazeilles** [CentroEPiaggio/dysturbance#3]
The root Readme is quite critical as it is automatically rendered by Github when go the the repository page.

I would thus suggest you to extend its content, and mention what can be found into the repository.
An example of Readme can be found in our [example page](https://github.com/eurobench/pi_octave_csic). 
Appart from the copyright and main content, it is also good practice indicating the funding support you got to make this development. You can find in our readme an example of acknowldegment to Eurobench & the European Commision.

Finally, it seems that this repository gathers the code used for the experimentation execution (dysturbace_ros), and the code used for the PI computation (Code_Dysturbance).

If this is like is, I would suggest using distinct code repository for these two aspects, as a separation of concerns matter.

**Comment by qbrobotics-AT** [comment]
Thanks @aremazeilles for the suggestions.

Unfortunately we have some constraints in the CentroEPiaggio organization so we have decided to put everything inside a single repository, but I agree with you that it is messy.

I'm going to discuss with @F-Neg and @simomonte on how we can handle this, maybe by creating a new distinct account to host all the required repositories.

By the way, I'm not sure if it is expected to have a single repository for each PI computation of if we can put all the protocol inside a single repository, as it is "Code_Dysturbance" right now.

**Comment by aremazeilles** [comment]
You can leave the two components in the same repo if it is more practical for you. As long as the readme defines what is where, then we can handle it as is I think. You could maybe use a more explicit folder name, like `code_pi`. But not mandatory neither I think.

> By the way, I'm not sure if it is expected to have a single repository for each PI computation of if we can put all the protocol inside a single repository, as it is "Code_Dysturbance" right now.

I don´t think we need a repository per PI. Having an entry point to the code per PI maybe preferrable, but we also expect to have a single code (like a main or an octave script) that launches the computation of several PIs. A folder containing code of all PI computation is therefore ok.

**Comment by qbrobotics-AT** [comment]
Ok, we try to arrange all the material in this repo first (with proper READMEs in main and sub directories).
If it is not enough we will split it.

**Comment by aremazeilles** [comment]
This issue about the global readme may be closed, right?
