### ISSUE TITLE
Call example of the matlab code

### ISSUE THREAD

**Issue by aremazeilles** [CentroEPiaggio/dysturbance#9]
Trying to launch the code from Matlab.

I try:

```matlab
run_local_pi("./tests/data/input/subject_1/protocol_1/subject_1_cond_1008203500/raw_data_input/subject_1_cond_1008203500_run_0_platformData.csv", "./tests/data/input/subject_1/protocol_1/subject_1_cond_1008203500/raw_data_input/subject_1_cond_1008203500_testbed.yaml", "./tests/data/input/subject_1/subject_1_info.yaml","./tests/data/output/subject_1/protocol_1")
```

But it fails with:

```term
Starting local PI computation...
Array indices must be positive integers or logical values.

Error in Compute_Local_PI (line 17)
name_of_file = FILENAME{1}(index(end)+1:end);

Error in run_local_pi (line 4)
  Compute_Local_PI(filename, yaml_file, subject_yaml, result_folder);
```

Could you indicate me how to call it correctly?

**Comment by qbrobotics-AT** [comment]
The code works fine on my Linux PC (Ubuntu 16.04) with MATLAB installed (r2020a).
```
>> cd Dysturbance_Pi/
>> run_local_pi("./tests/data/input/subject_1/protocol_1/subject_1_cond_1008203500/raw_data_input/subject_1_cond_1008203500_run_0_platformData.csv", "./tests/data/input/subject_1/protocol_1/subject_1_cond_1008203500/raw_data_input/subject_1_cond_1008203500_testbed.yaml", "./tests/data/input/subject_1/subject_1_info.yaml","./tests/data/output/subject_1/protocol_1")
Starting local PI computation...
Pre-processing Raw Data ...  
Extracting Data Structures ...  
Computing Normalization Factors ...  
Checking if the system fails ... 
Computing Local PI ... 
```
Are you calling it from Windows instead of Linux? Maybe the path should be changed accordingly to the Windows standards (with backslashes instead of slashes)?

Please let us know some more details to better understand the possible causes.

**Comment by aremazeilles** [comment]
I just have access to Matlab from my Window session. Could this be due to the filename path format?

**Comment by qbrobotics-AT** [comment]
I think so.
If you can try the command with the Windows absolute path (using "\" instead of "/") it should work fine.
Let us know if it still does not work.

**Comment by aremazeilles** [comment]
PLacing the file absolute path it gows further, but then I get:

```term
Starting local PI computation...
Pre-processing Raw Data ...  
'smooth' requires one of the following:
  Curve Fitting Toolbox
  Econometrics Toolbox
```

Which toolbox are you using?

**Comment by qbrobotics-AT** [comment]
I've only the Curve Fitting Toolbox installed, so I believe it is that one, but @simomonte should be able to confirm this thing.

**Comment by simomonte** [comment]
Hi! Yes, as Alessandro said, we used the curve fitting toolbox.
Best regards,
Simone

Il ven 30 apr 2021, 18:01 Alessandro Tondo ***@***.***> ha
scritto:

**Comment by aremazeilles** [comment]
It has been some time, but I could get Matlab on Linux, and with the cuve fitting toolbox, indeed it works.

Might be good indicating in the readme that the `curve fitting` toolbox is required.

**Comment by aremazeilles** [comment]
Could this be closed?
